version: "3.9"

services:
  gateway:
    build: ./API-Gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - agente_imagem
      - agente_llm

  agente_imagem:
    build: ./Agente-Imagem
    container_name: agente_imagem
    ports:
      - "5001:5001"

  agente_llm:
    build: ./Agente-LLM
    container_name: agente_llm
    ports:
      - "5002:5002"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
